"""report_builders/changelog_generator.py — INTERMEDIATE: build a CHANGELOG.md from JSON.

Reads a JSON file containing a list of release objects, each with:
  { "version": "x.y.z", "date": "YYYY-MM-DD", "entries": [{"type": "...", "description": "..."}] }

Change types are grouped within each version section.  Recognized types and their
display labels: feat, fix, improve, docs, chore, test, security, deprecate, break.

Example commands:
    python document_generation/report_builders/changelog_generator.py \\
        document_generation/examples/sample_changelog.json \\
        /tmp/CHANGELOG.md

    python document_generation/report_builders/changelog_generator.py \\
        document_generation/examples/sample_changelog.json \\
        /tmp/CHANGELOG.md \\
        --project "Orion Data Pipeline" \\
        --force
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

# Ordered display order for change types (less common ones fall to "Other")
_TYPE_ORDER = ["break", "security", "feat", "fix", "improve", "docs", "test", "chore", "deprecate"]

_TYPE_LABELS: dict[str, str] = {
    "break":      "Breaking Changes",
    "security":   "Security",
    "feat":       "New Features",
    "fix":        "Bug Fixes",
    "improve":    "Improvements",
    "docs":       "Documentation",
    "test":       "Tests",
    "chore":      "Chores",
    "deprecate":  "Deprecated",
}


def _type_label(t: str) -> str:
    return _TYPE_LABELS.get(t.lower(), t.title())


def _type_sort_key(t: str) -> int:
    try:
        return _TYPE_ORDER.index(t.lower())
    except ValueError:
        return len(_TYPE_ORDER)


def build_changelog(
    releases: list[dict],
    project_name: str | None = None,
    repo_url: str | None = None,
) -> str:
    """Build a CHANGELOG.md string from a list of release dicts.

    Args:
        releases:     List of release objects (version, date, entries).
        project_name: Optional project name for the document header.
        repo_url:     Optional repository URL for a header link.

    Returns:
        A multiline CHANGELOG.md string.
    """
    lines: list[str] = []

    # --- Document header ---
    if project_name:
        if repo_url:
            lines.append(f"# [{project_name}]({repo_url}) — Changelog\n")
        else:
            lines.append(f"# {project_name} — Changelog\n")
    else:
        lines.append("# Changelog\n")

    lines.append(
        "All notable changes to this project are documented in this file.  \n"
        "Format follows [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) conventions.\n"
    )

    # --- One section per release ---
    for release in releases:
        version = release.get("version", "Unreleased")
        date    = release.get("date", "")
        entries = release.get("entries", [])

        # Version heading (H2)
        heading = f"## [{version}]" if version != "Unreleased" else "## [Unreleased]"
        if date:
            heading += f" — {date}"
        lines.append(heading + "\n")

        if not entries:
            lines.append("_No entries._\n")
            continue

        # Group by type
        by_type: dict[str, list[str]] = defaultdict(list)
        for entry in entries:
            t = entry.get("type", "chore").lower()
            desc = entry.get("description", "")
            by_type[t].append(desc)

        # Emit in canonical order
        all_types = sorted(by_type.keys(), key=_type_sort_key)
        for t in all_types:
            lines.append(f"### {_type_label(t)}\n")
            for desc in by_type[t]:
                lines.append(f"- {desc}")
            lines.append("")  # blank line after each group

    lines.append("---")
    lines.append("_Generated by changelog_generator.py_")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a CHANGELOG.md from a JSON list of release entries.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("input",  type=Path, help="Input .json file (list of release objects).")
    parser.add_argument("output", type=Path, help="Output .md file to write.")
    parser.add_argument("--project", metavar="NAME", help="Project name for the document header.")
    parser.add_argument("--repo-url", metavar="URL",  help="Repository URL for the header link.")
    parser.add_argument(
        "--force", action="store_true", help="Overwrite the output file if it already exists."
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)

    if args.output.exists() and not args.force:
        print(f"[error] Output file already exists: {args.output}")
        print("        Use --force to overwrite.")
        sys.exit(1)

    if not args.input.exists():
        print(f"[error] Input file not found: {args.input}")
        sys.exit(1)

    with args.input.open(encoding="utf-8") as fh:
        releases = json.load(fh)

    if not isinstance(releases, list):
        print("[error] JSON root must be a list of release objects.")
        sys.exit(1)

    changelog = build_changelog(releases, project_name=args.project, repo_url=args.repo_url)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(changelog, encoding="utf-8")

    total_entries = sum(len(r.get("entries", [])) for r in releases)
    print(f"[ok] {len(releases)} versions, {total_entries} entries → {args.output}")


if __name__ == "__main__":
    main()
