from tqdm import tqdm

def get_required_files_list(
    args: argparse.Namespace, selected_macro_names: list[str]
) -> list[str] | None:
    """
    Gets required project files by running SOME_SCRIPT.pl script
    > Shows progress bar during execution and prints informational messages from the script in top of progress bar
    > Reads MYFILE.filenames.txt generated by the script and returns list of file paths
    """
    fname_MYFILE_filenames = "MYFILE.filenames.txt"
    if not os.path.exists(fname_MYFILE_filenames):
        try:
            cmd = [
                "/bin/csh",
                "-c",
                f"SOME_SCRIPT_TO_CALL",
            ]
            iprint("Running SOME_SCRIPT.pl to obtain required files list...")

            # Run command with subprocess to include interactive progress bar
            proc = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True
            )
            # Show progress bar while the script is running
            # Progress bar format: "Generating MYFILE.filenames.txt |████████████████████████| 100% 12s"
            with tqdm(
                total=100,
                desc="Generating MYFILE.filenames.txt",
                bar_format="{desc} |{bar}| {percentage:3.0f}% {elapsed}s",
                ncols=80,
                colour="magenta",
            ) as progress_bar:
                # Keep counter index to update progress bar
                i = 0
                while proc.poll() is None:
                    # Read line from stdout
                    line = proc.stdout.readline()
                    if line:
                        # If line is not empty and starts with -I-, print it above the progress bar
                        if line.startswith("-I-"):
                            tqdm.write(line.strip())
                            sys.stdout.flush()
                    # Update progress bar by 1% until it reaches 99%
                    progress_bar.update(1 if i < 99 else 0)
                    i += 1
                    time.sleep(0.01)
                # Reached 100% when process is done, refresh progress bar
                progress_bar.n = 100
                progress_bar.refresh()
            # If process return code is not 0, raise error
            if proc.returncode != 0:
                fatal_error("Failed to extract required files list")
        except Exception:
            fatal_error("Failed to extract required files list.")
    # Read MYFILE.filenames.txt which is generated by the SOME_SCRIPT.pl script
    with safe_open(fname_MYFILE_filenames, "r") as MYFILE_filenames_handle:
        fpath_MYFILE_filenames = MYFILE_filenames_handle.readlines()
    return fpath_MYFILE_filenames
