"""templating/yaml_report_generator.py — INTERMEDIATE: render a Markdown report from a YAML spec.

Reads a YAML report specification (see examples/sample_report.yaml) and renders it
to a Markdown file using a Jinja2 template.  By default the script uses a built-in
template; pass --template to supply your own .j2 file.

Example commands:
    python document_generation/templating/yaml_report_generator.py \\
        document_generation/examples/sample_report.yaml \\
        /tmp/report.md

    python document_generation/templating/yaml_report_generator.py \\
        document_generation/examples/sample_report.yaml \\
        /tmp/report.md \\
        --template document_generation/templates/report.md.j2 \\
        --force
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml
from jinja2 import Environment, StrictUndefined

# ---------------------------------------------------------------------------
# Built-in fallback Jinja2 template (used when --template is not given)
# ---------------------------------------------------------------------------

_BUILTIN_TEMPLATE = """\
# {{ report.title }}
{% if report.subtitle %}**{{ report.subtitle }}**{% endif %}

| Field | Value |
|-------|-------|
| Date | {{ report.date }} |
| Authors | {{ report.authors | map(attribute='name') | join(', ') }} |
{% if report.confidentiality %}| Confidentiality | {{ report.confidentiality }} |{% endif %}

---

## Table of Contents

{% for section in sections %}
{{ loop.index }}. [{{ section.title }}](#{{ section.title | slugify }})
{% endfor %}

---

{% for section in sections %}
## {{ section.title }}

{{ section.content | trim }}

{% if section.metrics is defined %}
| Metric | Value |
|--------|-------|
{% for m in section.metrics %}| {{ m.label }} | {{ m.value }} |
{% endfor %}
{% endif %}
{% if section.incidents is defined %}
| Incident ID | Severity | Date | Resolution (hrs) |
|-------------|----------|------|-----------------|
{% for i in section.incidents %}| {{ i.id }} | {{ i.severity }} | {{ i.date }} | {{ i.resolution_hrs }} |
{% endfor %}
{% endif %}
{% if section.action_items is defined %}
| Owner | Due Date | Task |
|-------|----------|------|
{% for a in section.action_items %}| {{ a.owner }} | {{ a.due }} | {{ a.task }} |
{% endfor %}
{% endif %}

---

{% endfor %}

*Generated by yaml_report_generator.py*
"""


# ---------------------------------------------------------------------------
# Jinja2 custom filter — slugify
# ---------------------------------------------------------------------------


def _slugify_filter(text: str) -> str:
    """Convert a heading string to a GFM anchor slug."""
    s = text.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-{2,}", "-", s)
    return s.strip("-")


# ---------------------------------------------------------------------------
# Core render logic
# ---------------------------------------------------------------------------


def render_report(spec: dict, template_str: str) -> str:
    """Render a report from a YAML spec dict using a Jinja2 template string.

    Args:
        spec:         Parsed YAML spec (must contain top-level keys 'report' and 'sections').
        template_str: Jinja2 template as a string.

    Returns:
        Rendered markdown string.
    """
    # autoescape stays off: this renders Markdown, not HTML — HTML-escaping
    # would corrupt the output. The template and data are local, not web input.
    env = Environment(
        undefined=StrictUndefined,
        autoescape=False,  # noqa: S701 - Markdown output, not HTML; see comment above
        keep_trailing_newline=True,
    )
    env.filters["slugify"] = _slugify_filter

    tmpl = env.from_string(template_str)
    return tmpl.render(**spec)


def load_yaml_spec(path: Path) -> dict:
    """Load and validate a YAML report spec."""
    with path.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise TypeError(f"YAML file must contain a mapping at the top level, got {type(data).__name__}.")
    if "report" not in data or "sections" not in data:
        raise KeyError("YAML spec must contain both 'report' and 'sections' top-level keys.")
    return data  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a multi-section Markdown report from a YAML spec using Jinja2.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("input",  type=Path, help="Input YAML report spec (.yaml / .yml).")
    parser.add_argument("output", type=Path, help="Output .md file to write.")
    parser.add_argument(
        "--template",
        type=Path,
        metavar="FILE",
        help="Optional Jinja2 template file (.j2).  Defaults to a built-in template.",
    )
    parser.add_argument(
        "--force", action="store_true", help="Overwrite the output file if it already exists."
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)

    if args.output.exists() and not args.force:
        print(f"[error] Output file already exists: {args.output}")
        print("        Use --force to overwrite.")
        sys.exit(1)

    if not args.input.exists():
        print(f"[error] Input YAML file not found: {args.input}")
        sys.exit(1)

    spec = load_yaml_spec(args.input)

    if args.template:
        if not args.template.exists():
            print(f"[error] Template file not found: {args.template}")
            sys.exit(1)
        template_str = args.template.read_text(encoding="utf-8")
        template_source = str(args.template)
    else:
        template_str   = _BUILTIN_TEMPLATE
        template_source = "<builtin>"

    rendered = render_report(spec, template_str)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")

    n_sections = len(spec.get("sections", []))
    print(f"[ok] Rendered {n_sections} sections (template: {template_source}) → {args.output}")


if __name__ == "__main__":
    main()
